### DISCUSSION TITLE
Has anyone figured out how to build an EDK2 project on GitHub actions ?

### DISCUSSION THREAD

**Discussion by xCuri0** [tianocore/edk2#3652] [General]
Hi I've been trying to get my EDK2 based project to build on GitHub actions but it ends up with the error 

```
d:\a\rebaruefi\rebaruefi\RebarUEFI\ReBarDxe\ReBar.dsc(12): error 0010: File name case mismatch
	ReBarUEFI\ReBarDxe\ReBarDxe.inf
	RebarUEFI\ReBarDxe\ReBarDxe.inf [in file system]
```

I think GitHub actions has some sort of issue with filename case sensitivity that EDK2 build doesn't like. Here's my workflow file if it's of any use [ReBarDxe.yml](https://github.com/xCuri0/ReBarUEFI/blob/master/.github/workflows/ReBarDxe.yml). Running the same exact commands on my PC works perfectly.

**Comment by lersi** [comment]
actually I have already done it.
you are more than welcome to have a look into my project.
project link: [https://github.com/lersi/edk2_project_template](https://github.com/lersi/edk2_project_template)

let me know if there is a problem integrating my project into yours.
If there is a problem, I will help you implement GitHub CI on your project.

anyways, I have looked into your code, and the code seams fine but there is one bug.
here is the bug:
```yaml
 - name: Download RebarUEFI
      uses: actions/checkout@v3
      with:
        # it clones to 'RebarUEFI' instead of 'ReBarUEFI'
        path: '.\RebarUEFI\'
```
